

#development: &db
#  adapter: mysql2
#  encoding: utf8
#  database: db_45531843n1
#  username: user45531843n1
#  password: Btlox1Zk
#  host:     zeta.railshoster.de

development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  <<: *db

  database: db_45531843n3
  username: user45531843n3
  password: 1sgmjYct
  host:     zeta.railshoster.de

production:
  <<: *db

  database: db_45531843n2
  username: user45531843n2
  password: qpmJSPB2
  host:     zeta.railshoster.de

