

development: &db
  adapter: mysql2
  encoding: utf8
  database: db_43801846n1
  username: user43801846n1
  password: VriImVkX
  host:     ny.railshoster.de

test:
  <<: *db

  database: db_43801846n3
  username: user43801846n3
  password: 3OLRCCbB
  host:     ny.railshoster.de

production:
  <<: *db

  database: db_43801846n2
  username: user43801846n2
  password: Le3HU1E5
  host:     ny.railshoster.de

